ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

chat/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
    path('api/users/<int:pk>', views.user_list, name='user-detail'),
    path('api/users', views.user_list, name='user-list'),
    path('logout', LogoutView.as_view(next_page='index'), name='logout'),
    path('register', views.register_view, name='register'),
    path('search/', views.search_view, name='search'),
    path('search/<str:username>', views.search_view, name='search_detail')
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
import datetime

from django.core.cache import cache


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    def last_seen(self):
        return cache.get('last_seen_%s' % self.user.username)
    
    def online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            if now > (self.last_seen() + datetime.timedelta(seconds=settings.USER_ONLINE_TIMEOUT)):
                return False
            else:
                return True
        else: 
            return False


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

chat/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from chat.models import Message, UserProfile
from chat.serializers import MessageSerializer, UserSerializer
from django.db.models import Q
import sqlite3
import psycopg2


def index(request):
    if request.user.is_authenticated:
        return redirect('chats')
    if request.method == 'GET':
        return render(request, 'chat/index.html', {})
    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
        else:
            return render(request, 'chat/index.html', {'err': 'User does not exist'})
        return redirect('chats')


@csrf_exempt
def user_list(request, pk=None):
    """
    List all required users, or create a new user.
    """
    if request.method == 'GET':
        if pk:
            users = User.objects.filter(id=pk)
        else:
            # sql1 = """SELECT receiver_id FROM chat_db.chat_message WHERE sender_id=(%s) AND message IS NOT NULL GROUP BY receiver_id;"""
            # sql2 = """SELECT sender_id FROM chat_db.chat_message WHERE receiver_id=(%s) AND message IS NOT NULL GROUP BY sender_id;"""
            # conn = sqlite3.connect('db.sqlite3')
            # cur = conn.cursor()
            # cur.execute(sql1, (request.user.id,))
            # l1 = cur.fetchall()
            # cur.execute(sql2, (request.user.id,))
            # l2 = cur.fetchall()
            conn = psycopg2.connect(user = "db_admin9",
                                    password = "password",
                                    host = "127.0.0.1",
                                    port = "5432",
                                    database = "chat_db")
            sql1 = """SELECT receiver_id FROM chat_message WHERE sender_id=(%s) AND message IS NOT NULL GROUP BY receiver_id;"""
            sql2 = """SELECT sender_id FROM chat_message WHERE receiver_id=(%s) AND message IS NOT NULL GROUP BY sender_id;"""
            cur = conn.cursor()
            cur.execute(sql1, (request.user.id,))
            l1 = cur.fetchall()
            cur.execute(sql2, (request.user.id,))
            l2 = cur.fetchall()
            x = [i[0] for i in l1]
            y = [i[0] for i in l2]
            res = list(set(x + y))
            users = User.objects.filter(id__in=res).exclude(id=request.user.id)
            #users = User.objects.all()
        serializer = UserSerializer(users, many=True, context={'request': request})
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        try:
            user = User.objects.create_user(username=data['username'], password=data['password'])
            UserProfile.objects.create(user=user)
            return JsonResponse(data, status=201)
        except Exception:
            return JsonResponse({'error': "Something went wrong"}, status=400)


@csrf_exempt
def message_list(request, sender=None, receiver=None):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


def register_view(request):
    """
    Render registration template
    """
    if request.user.is_authenticated:
        return redirect('chats')
    return render(request, 'chat/register.html', {})


def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('index')

    if request.method == "GET":
        sql = """SELECT receiver_id FROM chat_message WHERE sender_id=(%s) AND message IS NOT NULL GROUP BY receiver_id"""
        #conn = sqlite3.connect('db.sqlite3')
        conn = psycopg2.connect(user = "db_admin9",
                                password = "password",
                                host = "127.0.0.1",
                                port = "5432",
                                database = "chat_db")
        cur = conn.cursor()
        cur.execute(sql, (request.user.id,))
        l = cur.fetchall()
        x = [i[0] for i in l]
        users = User.objects.filter(id__in=x).exclude(id=request.user.id)
        # query = request.GET.get('q')
        # if query:
        #     users = User.objects.filter(username__contains=query)
        return render(request, 'chat/chat.html',
                      {'users': users})




def message_view(request, sender, receiver):
    if not request.user.is_authenticated:
        return redirect('index')
    if not request.user.id == sender:
        return redirect('index')
    if request.method == "GET":
        # conn = sqlite3.connect('db.sqlite3')
        # cur = conn.cursor()
        # cur.execute(sql, (sender, receiver))
        # l = cur.fetchall()
        # x = [i[0] for i in l]
        conn = psycopg2.connect(user = "db_admin9",
                                password = "password",
                                host = "127.0.0.1",
                                port = "5432",
                                database = "chat_db")
        sql = """SELECT sender_id FROM chat_message WHERE sender_id=(%s) AND receiver_id=(%s) AND NOT(message IS NULL);"""
        cur = conn.cursor()
        cur.execute(sql, (sender, receiver))
        l = cur.fetchall()
        x = [i[0] for i in l]
        users = User.objects.filter(id__in=x)

        return render(request, "chat/messages.html",
                      {'users': User.objects.exclude(id__in=x).exclude(username=request.user.username),
                       'receiver': User.objects.get(id=receiver),
                       'messages': Message.objects.filter(sender_id=sender, receiver_id=receiver) |
                                   Message.objects.filter(sender_id=receiver, receiver_id=sender)})

def search_view(request, username=None):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        users = []
        query = request.GET.get('q')
        if query:
            users = User.objects.filter(username__contains=query)
        return render(request, "chat/search.html", {'users': users})

templates/chat/chat.html
{% extends 'chat/index.html' %}
{% block body %}
<nav class="col s12 red lighten-1">
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">JustChat</a>
      <ul id="nav-mobile" class="right">
          <li><a href="">{{ request.user.username }}</a></li>
          <li><a href="{% url 'search' %}" target="_blank">Search</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>

</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3" id="usr">

        <div class="card">
            <div id="users" class="collection">
                
            </div>
        </div>
        </div>
        <div class="col s9" id="resp_board">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating red lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load staticfiles %}
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
            setInterval(() => {
                getUsers({{ request.user.id }}, doc => {
                    let list = ''
                    doc.map(userItem => {
                        list += userItem
                    })
                    $('#users').html(list)
                });
            }, 1000)
        })        

        
    </script>
{% endblock %}

templates/chat/index.html
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>

    </body>
    </head>

    <body>
    {% block body %}
        {% if err %}
            <div class="row" id="alert_box">
              <div class="col s12 m12">
                <div class="card red darken-1">
                  <div class="row">
                    <div class="col s12 m10">
                      <div class="card-content white-text">
                        <p>User doesn't exist</p>
                    </div>
                  </div>
                  <div class="col s12 m2">
                    <i class="fa fa-times icon_style" id="alert_close" aria-hidden="true"></i>
                  </div>
                </div>
               </div>
              </div>
            </div>
            <script>
                $('#alert_close').click(function(){
                    $( "#alert_box" ).fadeOut( "slow", function() {
                    });
                  });
            </script>
        {% endif %}
        <div class="section red lighten-1">
            <div class="container white-text center-align text">
            <h2><a href="/" style="color: antiquewhite">JustChat</a></h2>
            <p>Real-time messaging app</p>
            <div class="chip">
                <img src="http://seanmm.com/assets/images/tech/django.svg" class="white">
                Django
            </div>
            <div class="chip">
                <img src="http://materializecss.com/res/materialize.svg" class="white">
                MaterializeCSS
            </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Login
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">account_circle</i>
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">vpn_key</i>
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn blue waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}

  </html>

templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left red lighten-4" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <i class="material-icons prefix">account_circle</i>
                <input name="username" id="id_username" type="text" class="validate">
                <label for="id_username" data-error="Username already taken">Username</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <input name="password" id="id_password" type="password">
                <label for="id_password">Password</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <input name="password2" id="id_password2" type="password">
                <label for="id_password2">Repeat Password</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
            <div class="right">
                <button class="btn blue waves-effect waves-light pull-s12">Register</button>
            </div>
            </div>
        </div>
    </form>
    <script>
    $(function () {
        $('#register-form').on('submit', function (event) {
            event.preventDefault();
            var username = $('#id_username').val();
            if(username !== '')
            {
                var password = $('#id_password').val();
                if(password !== '' && password === $('#id_password2').val()){
                    register(username, password);
                }
                else{
                    alert("The passwords doesn't match!");
                }
            }
            else
                alert("Please enter a valid username!");
        })
    })
    </script>
{% endblock %}

templates/chat/search.html
<!-- <form method="GET" action="" id="searchform">
	{% csrf_token %}
    <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search..."/>
</form> -->
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        
        <title>Justchat</title>
      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href="{% static 'img/j-152-193314.png' %}">

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'img/j-144-193314.png' %}">

        <link rel="apple-touch-icon-precomposed" sizes="120x120" href="{% static 'img/j-120-193314.png' %}">

        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'img/j-114-193314.png' %}">

        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'img/j-72-193314.png' %}">

        <link rel="apple-touch-icon-precomposed" href="{% static 'img/j-57-193314.png' %}">

        <link rel="icon" href="{% static 'img/j-32-193314.png' %}" sizes="32x32">
    </head>
<body style="background-color: whitesmoke;">
<nav>
<div class="nav-wrapper">
  <form method="GET" action="" id="searchform">
    <div class="input-field">
		{% csrf_token %}
    	<input class="searchfield" id="searchbox" style="margin-left: 1%" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search..."/>
      	<!-- <label class="label-icon" for="searchbox"><i class="material-icons">search</i></label> -->
      	<i class="material-icons">close</i>
    </div>
  </form>
</div>
</nav>


{% for user in users %}
<div class="card">
	<div id="users" class="collection">
		<a href="/chat/{{ request.user.id }}/{{ user.id }}" id="user{{ user.id }}" class="collection-item row">
		<img src="https://www.shareicon.net/data/256x256/2016/10/20/846414_letter_512x512.png"  style="width: 2.666667%;" class="col s2">
			<div class="col s10">
				<span class="title" style="font-weight: bolder;font-size: 1.1rem;">{{ user.username }}</span>
			</div>
		</a>
	</div>
</div>
{% endfor %}
</body>